### ISSUE TITLE
Issue when logging in as parent

### ISSUE THREAD

**Issue by pmaranin** [bain3/pronotepy#12]
Hello !

My code is working fine when I am connecting to the student url with student l/p but it throws error when connecting to the parent url with parent l/p. client = pronotepy.Client works fine but then

cp = client.current_period  throws

c:\temp\pronote\pronotepy\pronoteAPI.py in current_period(self)
    221     def current_period(self) -> dataClasses.Period:
    222         """Get the current period."""
--> 223         id_period = self.parametres_utilisateur['donneesSec']['donnees']['ressource']['listeOngletsPourPeriodes']['V'][0][
    224             'periodeParDefaut']['V']['N']
    225         return dataClasses.Util.get(self.periods_, id=id_period)[0]
KeyError: 'listeOngletsPourPeriodes'

and messages = client.messages() throws 

c:\temp\pronote\pronotepy\pronoteAPI.py in messages(self)
    272         messages = self.communication.post('ListeMessagerie', {'donnees': {'avecMessage': True, 'avecLu': True},
    273                                                                '_Signature_': {'onglet': 131}})
--> 274         return [dataClasses.Message(self, m) for m in messages['donneesSec']['donnees']['listeMessagerie']['V']
    275                 if not m.get('estUneDiscussion')]
    276 
KeyError: 'listeMessagerie'

Am I doing something wrong or is this a problem with the parent data model ?

**Comment by bain3** [comment]
Hello!
I have checked the pronote api for any differences between the student and parent accounts. Since the parent account can manage multiple students, it has a different path to the period information. To make this work we would have to have a separate client that can switch between the different students. I guess i shouldn't be saying that this works for parent and teacher accounts then. _Thank you for reporting this!_

_PS: You are more than welcome if you want to add this functionality (or anyone else) :)_

**Comment by pmaranin** [comment]
I don't mind helping but I do not note the pronote json structure/format (hence why I am using your cool API)
If you give me some hint on where to look at on the pronote documentation, I am happy to give it a try...

**Comment by bain3** [comment]
Added parent support in e9e0024.

**Comment by pmaranin** [comment]
Thanks a lot !
