### ISSUE TITLE
Download all the files in the course contents in a given period of time

### ISSUE THREAD

**Issue by HevelMc** [bain3/pronotepy#13]
Hello,
I would like to know if there is an efficient way to download all the files in the course contents in a given period of time?

I have a program that doesn't always work and I know that using `lesson.content` is not very recommended.
```python
for lesson in client.lessons(date_from, date_to):
        if lesson.canceled != True and lesson.content != None:
            lfiles = lesson.content.files
            if len(lfiles) > 0:
                for lfile in lfiles:
                    print(lfile.name)
                    # download
```

And for some lessons he tells me that :
`contents = lesson['listeContenus']['V'][0]
IndexError: list index out of range`

Thanks in advance for your suggestions.

**Comment by bain3** [comment]
Hello,
sorry for the late reply. To fix the issue with downloading a lot of files at once, I suggest having a client cache of some sort that you could fill up using something like: `Client.fill_lesson_cache(date_from, date_to)`. The second issue you are having with it raising an `IndexError` is probably happening because pronotepy expects that the lesson will have some content. I'll have to look further into that.

**Comment by HevelMc** [comment]
Hello, thank you very much for your help. For the second error I haven't tried yet but I guess a try-except is enough to solve my problem.
On the other hand to download several files I don't know how to use a cache, would you have a doc about it ?

**Comment by bain3** [comment]
The cache was just a suggestion, it was not implemented. If someone wants to do it, just drop a comment here. I'll start working more on pronotepy when I'll have more time.
