### ISSUE TITLE
Users extension

### ISSUE THREAD

**Issue by ntala** [bain3/pronotepy#19]
Your project is really great. I have not so much free time theses days, but I will study it to learn how I can improve the interface so that teachers (and maybe parents) can use it.

Something sounds a bit weird for me : I thought that pronote and the others index-education application were mostly used in France. But the language used here seems to be English.

Can we speak French to each other ?

**Comment by Xiloe** [comment]
Hello there, to answer your question : yes Pronote is mostly used in French speaking countries, but it is also used in some other countries, like czech republic for example. The original owner of this repo being from there, I guess that's why the it is wrote in English.

Now if you want to make improvements to the API and add teacher/parents full support it would be awesome and we would like to review your pull request in details.

Yes we can speak French since I'm bilingual / native French speaker.

**Comment by Xiloe** [comment]
Added Parent support in [e9e002457d3d6332876670d196fa64380aacc31a](https://github.com/bain3/pronotepy/commit/e9e002457d3d6332876670d196fa64380aacc31a)
