### ISSUE TITLE
Extracting the list of subjects without specifying a time period.

### ISSUE THREAD

**Issue by jusdecitron** [bain3/pronotepy#229]
Hello !
It seems like we are unable to extract directly the list of subjects we are currently in unless we specify a certain period.

Is there an easier way to extract the list of subjects we are in (including the name of subject and the teacher's name) without specifying a period ?

Sincerely,
Citron.

**Comment by bain3** [comment]
Hi!
No it is not currently possible to get a list of the subjects without a period. I think this isn't possible at all, since subjects can change between periods. I've tried searching for an endpoint that we could call and the only thing that came up was `ListeMatieres`, which gave me an `Your rights are insufficient to conduct this operation.` error (student acc)...

**Comment by jusdecitron** [comment]
Found a workaround-ish but I still need to specify a period.

Here is the code:
`   start_date = datetime.datetime(2022, 9, 1)
    end_date = datetime.datetime.today()
    lessons = client.lessons(start_date, end_date)
    subjects = set((lesson.subject.name, tuple(lesson.teacher_names)) for lesson in lessons if lesson.subject)
    print(subjects)`

What do you think about it?

**Comment by jusdecitron** [comment]
Code update - it seems like there are some duplicates when printing `subjects`

Updated (it also sorts the subjects alphabetically):
`
courses = client.lessons(
        datetime.datetime(2022, 9, 1),
        datetime.datetime.today()
    )
    courses_data = sorted(
        set(
            (course.subject.name, tuple(course.teacher_names))
            for course in courses
            if course.subject and course.teacher_names
            and all(teacher_name for teacher_name in course.teacher_names)
        )
    )
`
