### ISSUE TITLE
Authentification with QR code

### ISSUE THREAD

**Issue by Emilien-B** [bain3/pronotepy#243]
Hi,
The PRONOTE application allows to connect with a QR code and to remain connected to each connexion.
How I can do the same ? 
I think I have to keep some data at the end of each connexion. I tried to do it but I did not succeed.

**Comment by bain3** [comment]
Hi,
the QR code login could be more documented. Things you need:

1. QR code data. Parse the QR code, get JSON from it, and then parse the JSON to get a dict (`qr_code`)
2. The PIN set when creating the QR code. It should be a string (`pin`)

You then create the client like so:

```py
client = pronotepy.Client.qr_login(qr_code, pin)
```

Up until this point it should work, and you should be able to use the client. The problem is that on each new connection you need a new password. The QR code expires in 10 minutes.

You can get the credentials for the next login from `client.username`, and `client.password`.

**Unfortunately logging in using the new credentials does not work currently, I'm going to look into it.**

**Comment by Emilien-B** [comment]
I already tried to use `client.username` and `client.password`. Now, I understand why I didn't succeed.
Thank you for dealing with it.

**Comment by MRakox** [comment]
I thought this problem was due to the fact that the UUID of the mobile application was regenerated each time. So I hard-coded it [here](https://github.com/bain3/pronotepy/blob/master/pronotepy/clients.py#L68) but that doesn't seem to solve the problem...

**Comment by bain3** [comment]
Hi, I've finished implementing the QR code login. The first login must be done through `Client.qr_login`, and subsequent logins should be through `Client.token_login` (see example below). You can install the version through pip using:

```
pip install -UI git+https://github.com/bain3/pronotepy@qrlogin
```

<details><summary>Example</summary>

```py
qr_code = ...
pin = ...

# first login through QR code
client = pronotepy.Client.qrcode_login(qr_code, pin, "myRandomUuid")

# ... next login through the token received after logging in previously
client = pronotepy.Client.token_login(client.pronote_url, client.username, client.password, "myRandomUuid")

# ... next login through the token received after logging in previously
client = pronotepy.Client.token_login(client.pronote_url, client.username, client.password, "myRandomUuid")
```

</details> 

Pronotepy will now additionally come with a script to generate these password tokens. You can run it using:
```
python3 -m pronotepy.create_login
```
(you need to be able to either read the qr code contents, or login through pronotepy using user/pass)

**Comment by bain3** [comment]
If it can bypass ENTs then I think this will be the new preferred login method. We won't have to maintain a DB of ENTs, and users won't have to keep their passwords available for logging in.

**Comment by tarneaux** [comment]
I'll probably be able to test it on Monday, if the administrators of my ENT decide to let me login again by then.

But in theory it should all work, since it does for the official app.

This is a great feature to have, since it allows minimizing the (probably already low) damage a token leak would cause.

**Comment by bain3** [comment]
I've forgot to mention that you can also generate new QR codes using `Client.request_qr_code_data(pin)`

**Comment by tarneaux** [comment]
First off, when running `python3 -m pronotepy.create_login` and leaving the first field empty, the following error is raised:
```
JSON QR code contents (leave blank for user/pass login):
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/create_login.py", line 53, in <module>
    main()
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/create_login.py", line 9, in main
    qr_code = json.loads(
              ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
So apparently the path for the user/pass login is not handled correctly.

> I forgot to mention that you can also generate new QR codes using `Client.request_qr_code_data(pin)`

Should we not integrate this into a CLI command, so that the user doesn't have to make an entire program just to get QR JSON data? I'm guessing this is the inteded behavior of leaving the first answer in the `python3 -m pronotepy.create_login` helper empty. Do note it should also ask for which ENT we want to use.


Now, when scanning the QR, extracting the JSON data it gives and pasting that to the field, everything works well.

When first trying to connect with `token_login` with the following code:
```python
import pronotepy
import datetime


client = pronotepy.Client.token_login(
        "https://[redacted].index-education.net/pronote/mobile.eleve.html?login=true",
        "mpothier",
        "[redacted_long_token]",
        "[redacted_uuid]"
    )

for lesson in client.lessons(date_from=datetime.date.today(), date_to=datetime.date.today() + datetime.timedelta(weeks=1)):
    print(lesson.classroom, lesson.subject.name, lesson.teacher_name, lesson.start, lesson.end)
```

Error: `pronotepy.exceptions.CryptoError: ('Decryption failed while trying to un pad. (probably bad decryption key/iv)', 'exception happened during login -> probably bad username/password')`

<details><summary>Full log</summary>

```
Traceback (most recent call last):
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 327, in aes_decrypt
    return Padding.unpad(cipher.decrypt(data), 16)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted]/pronotepy-qr/test.py", line 6, in <module>
    client = pronotepy.Client.token_login(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 154, in token_login
    return cls(pronote_url, username, password, mode="token", uuid=uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 390, in __init__
    super().__init__(pronote_url, username, password, ent, mode, uuid)
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 104, in __init__
    self.logged_in = self._login()
                     ^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 207, in _login
    dec = e.aes_decrypt(bytes.fromhex(challenge))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 329, in aes_decrypt
    raise CryptoError(
pronotepy.exceptions.CryptoError: ('Decryption failed while trying to un pad. (probably bad decryption key/iv)', 'exception happened during login -> probably bad username/password')
```
</details>

I noticed the URL contained `/mobile.eleve.html?login=true` instead of the usual `/eleve.html` and so changed it.

Error: `pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.`

<details><summary>Full log</summary>

```
Traceback (most recent call last):
  File "[redacted]/pronotepy-qr/test.py", line 6, in <module>
    client = pronotepy.Client.token_login(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 154, in token_login
    return cls(pronote_url, username, password, mode="token", uuid=uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 390, in __init__
    super().__init__(pronote_url, username, password, ent, mode, uuid)
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/clients.py", line 81, in __init__
    self.attributes, self.func_options = self.communication.initialise()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 76, in initialise
    self.attributes = self._parse_html(get_response.content)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/pronotepy-qr/venv/lib/python3.11/site-packages/pronotepy/pronoteAPI.py", line 263, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```
</details>

I confirmed the cause was the `token_login()` method by running the following, which successfully printed my upcoming lessons:
```python
import pronotepy
from pronotepy.ent import [redacted_ent]
import datetime


client = pronotepy.Client(
        "https://[redacted].index-education.net/pronote/mobile.eleve.html?login=true",
        "[redacted_username]",
        "[redacted_pass]",
        ent=[redacted_ent]
    )

for lesson in client.lessons(date_from=datetime.date.today(), date_to=datetime.date.today() + datetime.timedelta(weeks=1)):
    print(lesson.classroom, lesson.subject.name, lesson.teacher_name, lesson.start, lesson.end)
```

From this testing (and some more), we can conclude the following:

- When trying to connect with a token and any of the following URLs, a `pronotepy.exceptions.CryptoError` occurs.
  - `https://[redacted].index-education.net/pronote/mobile.eleve.html?login=true`
  - `https://[redacted].index-education.net/pronote/eleve.html?login=true`
- When trying to connect with a token and any of the following URLs, a `pronotepy.exceptions.PronoteAPIError` occurs.
  - `https://[redacted].index-education.net/pronote/mobile.eleve.html`
  - `https://[redacted].index-education.net/pronote/eleve.html`
- -> the `?login=true` part of the URL causes a `CryptoError`, but using `mobile.eleve.html` or just `eleve.html` changes nothing.
- When trying to connect with any of the four URLs mentioned above but with username/pass/ENT, everything works well.

-> something is wrong with `token_login()`.

Furthermore, when adding a debug print in `pronoteAPI.py` just before the exception is raised, we can see the folliwing HTML:
<details><summary>HTML page</summary>

```
<!doctype html>
<!--

 -->

<html>
	<head>
		<title>Authentification</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<script type="text/javascript" src="/assets/js/entcore/ng-app.js?v=1693814461887" id="context"></script>
		<script type="text/javascript" src="/auth/public/dist/application.js?v=1693814461887"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <script type="text/javascript">var notLoggedIn = true;</script>
	</head>
	<body class="login" ng-controller="LoginController"
		  ng-init='error = ""; callBack = ""; mainPage = ""'>
		<default-styles>
			<div class="absolute">
             <div ng-include="template.containers.main"></div>
            </div>
		</default-styles>
	</body>
</html>
```
</details>
... which happens to be the HTML of my ENT's login page.

**Comment by tarneaux** [comment]
> Interesting. I don't know what's happening here. When you use the QR code with the official mobile app, it doesn't require you to go through your ENT, no?

I've been using Papillon for more than half a year so I'm not 100% sure, but I don't think it uses the ENT. To me that's the purpose of the QR code

**Comment by bain3** [comment]
Damn I don't know. Works on my machine™...

![screenshot of a terminal showing successful output](https://bain.cz/t/6c08fdd514da.png)

I have fixed the `create_login` problem
