### ISSUE TITLE
Modifications de Pronote 2023

### ISSUE THREAD

**Issue by Merlode11** [bain3/pronotepy#261]
Bonjour,

J'ai vu que Pronote a légèrement changé sa manière de fonctionner pour accepter ses requêtes pour cette nouvelle année 2023. En ayant repris l'API en JavaScript de Livartan, je l'utilise quotidiennement pour un bot Discord.
Cependant, avec les changements opérés sur Pronote 2023, l'API que j'utilisais ne fonctionne plus. J'ai un peu cherché le problème mais je n'ai pas trouvé de solution convenable à ce jour pour régler le problème.

J'ai pu voir sur l'évolution de votre code que vous avez pu palier à ces modifications avec des changements dans votre code. 
Est-ce qu'il serait possible pour vous de m'indiquer ce qui a changé dans la manière de Pronote pour traiter ces requêtes, et de la manière dont vous avez réussi à palier ceci ?

Je vous remercie grandement d'avance pour votre réponse,
Cordialement,
Merlode

**Comment by bain3** [comment]
Hi, the biggest change was that you no longer receive keys for RSA encryption from the HTML ("ER" and "MR" attributes). They are hard-coded instead.

In the `FonctionParametres` request, the `Uuid` field is no longer encrypted when using HTTPS connections. You don't use the RSA encryption at all. So basically, if you're only worried about HTTPS connections, then you just simply remove any mentions of RSA encryption, and that should be it.

The compatibility was fixed in ed2040c. You can find the necessary changes there.
