### ISSUE TITLE
How can I get the grades and the average of the trimester and not of all the period

### ISSUE THREAD

**Issue by Bapt5** [bain3/pronotepy#31]
Hello 
I'm trying to the grades and the average of the trimester and not of all the period. How can I do that ?

**Comment by AlexZeGamer** [comment]
A period represents a trimester
(https://pronotepy.readthedocs.io/en/stable/quickstart/#grades)

**Comment by Bapt5** [comment]
Yes It is that I thought but when I get the grade of the current period I have all the grade of the year

**Comment by bain3** [comment]
Hello, we get the current period directly from pronote, so it might just be that you only have one big period. All grades have a `date` attribute so you can filter by that. Otherwise you could try finding the correct period by selecting one from `client.periods` by its attributes like `start` or `name`.

**Comment by Bapt5** [comment]
Ok Thank you I think my school has not set the good period I will try wuith your method
