### ISSUE TITLE
Marks in pronotepy please ? 

### ISSUE THREAD

**Issue by dathosim** [bain3/pronotepy#84]
Hi,

your api is great ! 
I use to display timetable  and homework in Home Assistant for my kids
I send notification when a lessons is cancelled, I adjust alarm clock automatically with the hour of first lesson of the day (- 1 hour)...
Many thanks !

Now, I would like to get marks.
It's possible to add this in your API please ?

**Comment by bain3** [comment]
Hello!
First of all very nice project! Marks are supported although they're called grades in pronotepy. You can access them using pronotepy.Client.[current_period](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.clients/#pronotepy.clients.Client.current_period).[grades](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.dataClasses/#pronotepy.dataClasses.Period.grades). You can access all periods using `pronotepy.Client.periods`. I've just now noticed that the `periods` property is not in the documentation because it is on the `_ClientBase` class. I'll fix that.

**Comment by dathosim** [comment]
Hello ! Thanks a lot ! 
I didn't read the documentation properly.
It's work - I can get new grade/mark and send notification (with home assistant)
